### PR TITLE
Feature #27: Tab View

### LINKED ISSUE #27: Feature: Tab views
# Description
Implement the tab view to change between Strategies and Deployment

### PR DESCRIPTION
**Pull request by andre-meyer**
# Description

Closes #27 

Implements a "tab view" to select either "deployment" or "strategies" - it also changes the default tab to the deployment tab according to the designs. 

# To Test
- [ ] Switching between tabs should work
- [ ] Counter Badge should be shown on numbers
- [ ] Counter Badge should change color when the tab is active

# Background

Additionally some changes were made:
- New Component to render text with a big badge, according to design
- Refactored the `Active` route into `Strategies`, having an index and 3 files for each individual type of Strategy filter

### CODE REVIEW

**Review by alfetopito — APPROVED** [review]
Very nice, works smoothly.

No blockers on the code other than, would it be too much effort to make the new files typescript?
I'd like to have everything new as TS to make the migration easier and reduce technical debt.

Unless this will delay any milestone we might have, I'll leave up to your discretion.

**Comment by andre-meyer** [comment]
> No blockers on the code other than, would it be too much effort to make the new files typescript?
> I'd like to have everything new as TS to make the migration easier and reduce technical debt.
> 
> Unless this will delay any milestone we might have, I'll leave up to your discretion.

Thansk for the review! I won't be changing the files to `.ts` right now, I will do it asap after the Demo today.

**Comment by andre-meyer** [comment]
Added to demo cleanup PR

**Comment by elena-zh** [comment]
Works fine. However, there are some cases exist:
- all the fields on the Deploy tab are cleared out when switch to the Strategies tab
- screen on the Strategies tab is flickering each 10 sec

 As it is discussed, it will be scoped later

**Pull request closed without merging**
