### PR TITLE
Post deploy action

### PR DESCRIPTION
**Pull request by alfetopito**
# Description

Reset deploy form after submission.

# To Test
1. On Deploy page, fill in all the required fields.
2. Once submit button is enabled, submit.

- [ ] Safe tx modal should appear.

3. Cancel OR submit the tx, up to you

- [ ] Deploy form should be reset

# Background

N/A

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 * **🔐 [Safe app link](https://pr171--safecmmappreact.review.gnosisdev.com)**: To be added as a custom app on [Safe Multisig Rinkeby](https://rinkeby.gnosis-safe.io/), [Mainnet](https://gnosis-safe.io/) or [xDai](https://xdai.gnosis-safe.io)
 * **📖 [Storybook](https://pr171--safecmmappreact.review.gnosisdev.com/storybook/)**: Component stories

**Comment by andre-meyer** [comment]
Test failed?
image

**Comment by andre-meyer** [comment]
Actually don't know if this is related to the change you made. Still, I couldn't test it 🙈

**Comment by alfetopito** [comment]
> Test failed?
> image

The failure is unrelated to the change. But it has to be fixed anyway.
I'll work on it.

**Comment by alfetopito** [comment]
@andre-meyer tried both on rinkeby and xdai with same parameters as you but couldn't reproduce yet :/

Anything else particular about your setup?

**Comment by andre-meyer** [comment]
I found this issue an fixed it in a different commit. It was related to the precision being so high (more than 18 decimals) that the multiplication with 1e18 still left decimal places, which BN didn't like. It was in priceToBn:
https://github.com/gnosis/safe-cmm-app-react/commit/d090fc1e7eb0d3808f00ce94dc173d352b168c22

**Review by andre-meyer — APPROVED** [review]

**Comment by alfetopito** [comment]
> I found this issue an fixed it in a different commit. It was related to the precision being so high (more than 18 decimals) that the multiplication with 1e18 still left decimal places, which BN didn't like. It was in priceToBn:
> [d090fc1](https://github.com/gnosis/safe-cmm-app-react/commit/d090fc1e7eb0d3808f00ce94dc173d352b168c22)

Huh. Thanks for finding it out.

Regarding this function, was meant to be temporary anyway.
I don't think we should store the price representation in BNs in the first place, because price essentially will need a decimal representation.

Another technical debt to clear.

**Pull request merged**
