### PR TITLE
Release 0.4.1

### PR DESCRIPTION
**Pull request by alfetopito**
# Description

**Release 0.4.1**

Minor version with a couple of fixes

# Change list
- Post deploy action (#171) - clearing form after submit
- Feature/#153/onboarding modal layout footer (#173) - finished onboarding modal layout
- Multiple ui fixes (#195)
- Total value claimable (#196) - on closed tab
- Feature/#176/deployed params (#197) - filled in missing data
- Feature #190: Pending screen deployed params (#198)
- Make pending and closed table rows clickable (#200)

### CODE REVIEW

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 * **🔐 [Safe app link](https://pr201--safecmmappreact.review.gnosisdev.com)**: To be added as a custom app on [Safe Multisig Rinkeby](https://rinkeby.gnosis-safe.io/), [Mainnet](https://gnosis-safe.io/) or [xDai](https://xdai.gnosis-safe.io)
 * **📖 [Storybook](https://pr201--safecmmappreact.review.gnosisdev.com/storybook/)**: Component stories

**Comment by alfetopito** [comment]
Tested the whole flow on rinkeby:
- Deploy
- Pending (multi owners)
- Withdraw
- Claim

No issues so far

**Comment by alfetopito** [comment]
xDai withdrawal is not working

Fix: https://github.com/gnosis/safe-cmm-app-react/pull/202

**Comment by alfetopito** [comment]
Everything working fine on xDai now

**Pull request merged**
